alias translate="trans -shell en:pt+br"
alias b="bundle"
alias bu="b update"
alias be="b exec"
alias rs="rails s"
alias rc="rails c"
alias 'gst'="git status"
alias 'gci'="git commit"
alias 'gco'='git checkout'
alias 'gm'='git merge'
alias 'gb'='git branch'
alias 'gll'="git pull"
alias 'gsh'="git push"
alias 'gadd'="git add --all"
alias 'gl'="git lg"
alias 'gf'="git fetch -p"
alias 'pryc'='pry -r ./config/environment'
alias 'br'='be rake'
alias 'brc'='be rails c'
alias 'brs'='be rails s'
alias 'bem'='br db:migrate db:test:prepare'
alias 'dropdb'='br db:drop db:create db:migrate db:seed db:test:prepare'
alias 'brr'='br routes'
alias 'bpec'='be rspec'

alias 'open'='xdg-open'
alias 'prj'='cd $HOME/projects'
