alias b="bundle"
alias bu="b update"
alias be="b exec"
alias 'gst'="git status"
alias 'gci'="git commit"
alias 'gco'='git checkout'
alias 'gm'='git merge'
alias 'gb'='git branch'
alias 'gpull'="git pull"
alias 'gpush'="git push"
alias 'gadd'="git add --all"
alias 'pryc'='pry -r ./config/environment'
alias 'br'='be rake'
alias 'brc'='be rails c'
alias 'brs'='be rails s'
alias 'bem'='br db:migrate db:test:prepare'
alias 'dropdb'='br db:drop db:create db:migrate db:seed db:test:prepare lancelote:generate_data'
alias 'brr'='br routes'
alias 'bpec'='be rspec'
alias 'mysql'='mysql -u root'
